### ISSUE TITLE
Multiple include problem

### ISSUE THREAD

**Issue by Walkeryr** [at0g/nunjucks-loader#10]
Hi,

I've got problem rendering template with nunjucks-loader.

    {% macro Slider(slides) -%}
    <div class="Slider">
        {% if slides|length %}
            <div class="Slider-contents">
                {% for s in slides %}
                    <div class="Slider-slide" data-order="{{ loop.index }}">
                        <div class="Frame Frame--simple"></div>

                        <a class="Slider-link u-Heading" href="">
                        <span class="Slider-linkContents">
                            <span class="Slider-titleContainer">
                                <span class="Slider-title">{{ s.title|safe }}</span>
                            </span>
                            <span class="Slider-linkMessage">Подробнее</span>
                        </span>
                        </a>

                        <div class="Slider-overlay"></div>

                        <img src="{{ s.img.main }}" srcset="{{ s.img.main_2x }} 2x" alt="{{ s.title }}"
                             class="Slider-img">
                    </div>
                {% endfor %}
            </div>

            <div class="Slider-counter">
            <span class="Slider-currentCounter">
                <span class="Slider-numberValue">01</span>
            </span>
                <span>of</span>
                <span class="Slider-numberTotal">{{ '%02d' % loop.length }}</span>
            </div>

            <button class="Slider-btn Slider-btn--prev u-Btn">
                {% include 'front/components/Slider/Slider-prev.svg' %}
            </button>

            <button class="Slider-btn Slider-btn--next u-Btn">
                {% include 'front/components/Slider/Slider-next.svg' %}
            </button>
        {% endif %}
    </div>{{ caller() }}
    {%- endmacro %}

This macro is rendered inside another template

    {%- import 'front/components/Slider/Slider.jinja' as Slider -%}

    <div class="IndexPage">
        {% call Slider.Slider(projects) %}{% endcall %}

        {% include 'front/components/Footer/Footer.jinja' %}
    </div>

I've got error in browser console:

Uncaught (in promise) Error: (unknown path) [Line 3, Column 23]
  RangeError: Maximum call stack size exceeded
    at Object.exports.withPrettyErrors (http://127.0.0.1:8000/static/js/front/app.js:1962:18)
    at Obj.extend.render (http://127.0.0.1:8000/static/js/front/app.js:3565:21)
    at render (http://127.0.0.1:8000/static/js/front/app.js:1369:38)
    at http://127.0.0.1:8000/static/js/front/app.js:1351:24

If I remove includes:
     {% include 'front/components/Slider/Slider-next.svg' %}
     {% include 'front/components/Slider/Slider-prev.svg' %}
Everything compiles fine

My webpack config: 
https://gist.github.com/Walkeryr/44783b973b6b6a27980e

Maybe this issue is connected with this one (similar in browserify):
https://github.com/mozilla/nunjucks/issues/492

**Comment by at0g** [comment]
Hi there! 
Thanks for the bug report - I'm swamped with work this week, but will look into it as soon as I get a chance.

**Comment by Walkeryr** [comment]
Problem happens in all browsers.
```lookup: function(name)``` — called recursively.

The problem is that same includes are resolved ok, in other templates.
I'll try to prepare example with isolated bug.

**Comment by dschissler** [comment]
I setup a skeleton a few months ago to test features and everything was working but for quite some time I've had that come commented out in my project.  I just became aware of this issue but downgrading to nunjucks-loader 1.0.7 and nunjucks 1.3.4 resolves this issue.  I'm just going to hang back for a while.

**Comment by at0g** [comment]
Hi @Walkeryr - can you provide me with an example repo that replicates your issue?

I've written a basic test of including a file within a macro and cannot replicate.

Test
https://github.com/at0g/nunjucks-loader/blob/master/test/spec/includes.js#L18-L22

Template
https://github.com/at0g/nunjucks-loader/blob/master/test/fixtures/templates/include-within-macro.nunj

Macro
https://github.com/at0g/nunjucks-loader/blob/master/test/fixtures/templates/macros.nunj

**Comment by Walkeryr** [comment]
Hi @at0g, with simple cases includes and imports work ok. But with more elements and nested templates something breaks.

I've created example with bug and deployed it here: https://github.com/Walkeryr/nunjucks-loader-example.

**Comment by at0g** [comment]
Hi @Walkeryr - thanks for making the example repo.

I see your issue and I'm positive it's caused by the svg file being included - try changing [the svg include](https://github.com/Walkeryr/nunjucks-loader-example/blob/master/app/components/Slider/Slider.jinja#L46) to include another `.jinja` file and you'll see  the macro works.

For inlining the svg into the templates, as of the 2.1.x version of nunjucks-loader, you can use a 'require' filter in your templates to resolve using webpacks require.

eg.

```
{{ 'svg-loader!path/to/svg.svg' | require }}
```

Anyway, I hope this solves your problem. Let me know how you get on.

**Comment by Walkeryr** [comment]
Hi @at0g, thank you very much for help!

Yes, svg causes this, I planned to use include tag as way to include raw content.
But your solution will fit me also. The problem is that with the latest releases of nunjucks-loader 2.1.0 my build breaks 

    /Users/mac/Projects/offcon/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:81
		r.forEach(function(r) {
		  ^
    TypeError: undefined is not a function
    at /Users/mac/Projects/offcon/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:81:5
    at Array.reduce (native)
    at LoadersList.match (/Users/mac/Projects/offcon/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:80:27)
    at NormalModuleFactory.<anonymous> (/Users/mac/Projects/offcon/node_modules/webpack/lib/NormalModuleFactory.js:109:65)
    at /Users/mac/Projects/offcon/node_modules/webpack/node_modules/async/lib/async.js:697:13
    at /Users/mac/Projects/offcon/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/mac/Projects/offcon/node_modules/webpack/node_modules/async/lib/async.js:248:21)
    at /Users/mac/Projects/offcon/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/mac/Projects/offcon/node_modules/webpack/node_modules/async/lib/async.js:694:17
    at /Users/mac/Projects/offcon/node_modules/webpack/node_modules/async/lib/async.js:173:37

My node version — v0.12.4. Not sure if it is connected with my node. Cause build is succesful with nunjcuks-loader 2.0.7.

**Comment by at0g** [comment]
That looks like a problem from webpack... If you got this message after adding the `svg-loader` bit, you need to `npm install svg-loader`.
 If not maybe check your webpack config, and/or do a clean install of your npm packages.
