### ISSUE TITLE
nunjucks-loader 2.1 cannot find the path of my nested template

### ISSUE THREAD

**Issue by dschissler** [at0g/nunjucks-loader#14]
Version 1.3 works fine but I cannot upgrade due to a blocker.  I'll try to reproduce this in a script when I need a break from CSS.

```
 Template render error: (unknown path) [Line 4, Column 6]
  Template render error: (unknown path)
  Template render error: (unknown path)
  Error: Unable to call `tab`, which is undefined or falsey
```

Here is template.nunjucks:

```
{% include './tab' %}

<div>
{% for item in items %}
  {{ tab(item) }}
{% endfor %}
</div>
```

and tab.nunjucks

```
{% macro tab(item) %}
<a class="ctrl-modal ctrl-modal-icon ctrl-modal-icon-{{item.icon}}" href="https://url.com" title="{{item.label}}">
  {{item.label}}
</a>
{% endmacro %}
```

**Comment by at0g** [comment]
Perhaps it will work if you `import` rather than `include` the macro?

https://mozilla.github.io/nunjucks/templating.html#import

>>> import loads a different template and allows you to access its exported values. Macros and top-level    assignments (done with set) are exported from templates, allowing you to access them in a different template.

**Comment by dschissler** [comment]
@at0g Thanks.  That got me through that error.  Now I'll have to open a new one for the next immediate issue.
