### ISSUE TITLE
nunjucks-loader is having issues with addGlobal with Babel 6

### ISSUE THREAD

**Issue by dschissler** [at0g/nunjucks-loader#22]
https://github.com/babel/babel-loader/issues/166#issuecomment-170257552

I've had to disable my translation calls in the templates until I can figure this out.  Also bluebird polyfill can't be found.

```javascript
'use strict';
// let locale = require('locale');
let locale = require.resolve('locale');

module.exports = function(env) {
  env.addGlobal('gettext', function(message) {
    return locale.gettext(message);
  });
  env.addGlobal('t', function(message) {
    return locale.gettext(message);
  });
  env.addGlobal('ngettext', function(msg1, msg2, n) {
    return locale.ngettext(msg1, msg2, n);
  });
  env.addGlobal('n', function(msg1, msg2, n) {
    return locale.ngettext(msg1, msg2, n);
  });
};
```

**Comment by at0g** [comment]
I'd appreciate if you stop creating issues that have nothing to do with this project.
nunjucks-loader does not even use babel.

**Comment by dschissler** [comment]
@at0g I'm not putting blame on this project but I'm surprised that you think that it is unreasonable to create a dialog about issues that numerous people will have when using this project.  Increasingly few people are writing in pure native Javascript these days as they are using Typescript, Babel, Coffeescript, etc.  That is how the real world is working TODAY.  At least now when people do a search they will see that this is an issue an can decide for themselves if they want to spend a lot of time trying to resolve it themselves or to let other people figure it out.

**Comment by at0g** [comment]
Personally I would be inclined to create the issue where I believe the problem exists (or can be fixed).

If you believe the issue can be fixed by changes to the code in this repository, I welcome the pull request.
