### ISSUE TITLE
I need to use to be able to resolve my modules and webpack node_modules in the loader

### ISSUE THREAD

**Issue by dschissler** [at0g/nunjucks-loader#3]
I am unable to configure nunjucks-loader to use my app modules.  I have a module called locale that does some fancy async downloading of the correct locale and I am unable to configure the loader to be able to access these in a global function.

Below the locale module is a custom one.

**nunjucks.config.coffee**

```coffeescript
'use strict'

locale = require 'locale'

# I added this to see if node modules can be found
require 'path'

module.exports = (env) ->

  env.addGlobal 'gettext', (message) -> locale.gettext message
  env.addGlobal 't', (message) -> locale.gettext message
  env.addGlobal 'ngettext', (msg1, msg2, n) -> locale.ngettext msg1, msg2, n
  env.addGlobal 'n', (msg1, msg2, n) -> locale.ngettext msg1, msg2, n

  null
```

**webpack.config.coffee**
```coffeescript
  resolveLoader:
    root: nodeModulesRoot
    modulesDirectories: [appModulesRoot, nodeModulesRoot, bowerRoot]
```

It is complaining with the following.  'jed' is a translation library in the bowerRoot.

```
ERROR in ../app/webpack/entries/app.site/partials/layout.nunj
Module build failed: Error: Cannot find module 'jed'
```

**Comment by at0g** [comment]
My understanding is that `addGlobal` is for adding simple values - the nunjucks docs make no mention of a third parameter when calling `addGlobal`, so it's probably not suitable for returning an async result.

In the `nunjucks.config.coffee` example, your globals are functions that expect input rather than just being values. Have you tried changing the `env.addGlobal` lines to `env.addFilter`? `addFilter` will work with async values if passed true as a third parameter.

**Comment by dschissler** [comment]
The issue is resolving modules and including them from the nunjucks config file.  Will using addFilter do anything in this regard?  I think that somehow it all needs to be wrapped in another layer so that webpack can find the paths.  If I attach a function to something then webpack/commonjs will take care of resolving anything in that function if it is known ahead of time.  It works properly in the [handlebars-loader](https://github.com/altano/handlebars-loader) code.  Perhaps you can see something there that is obvious.

I have addGlobal working with my previous nunjucks-loader code but it does so in actual module code.  Its for attaching anything scalar or a function.  It shouldn't care and webpack should take care of resolving in any function called if the function is statically defined.  Also I don't think that the filter idea works because there are three input variables and its not useful to pipe things into it.  Additionally gettext invocations need to be parsed and that is an separate project and I already went down that path with that parser.

**Comment by at0g** [comment]
ok, I've been trying to replicate the problem and think I see it now.

When entries are added to `resolve.root` or `resolve.modulesDirectories` in webpack.config, those module paths are not interpreted when resolving requires within the nunjucks config file.

Removing these two lines got rid of the compilation error for me:
https://github.com/at0g/nunjucks-loader/blob/master/index.js#L27-L28

and the environment still gets configured here: 
https://github.com/at0g/nunjucks-loader/blob/master/index.js#L52

however, it's not a good fix - async filters will no longer work as they must be added to the environment before the templates are compiled.

Anyway, I'm going to ask for some help on the webpack repo...

**Comment by dschissler** [comment]
https://github.com/webpack/webpack/issues/1033#issuecomment-99103743

**Comment by at0g** [comment]
`this.resolve` does not help - it just gives the absolute path to the config file but the dependencies within that file are still not resolved as expected.

**Comment by dschissler** [comment]
Is there any movement on this?

**Comment by at0g** [comment]
No movement until I hear back from webpack regarding #1038.

**Comment by dschissler** [comment]
Damn, I'm at a point now where I need this but the source is incomprehensible to me.

**Comment by at0g** [comment]
hey @dschissler, over the weekend I attempted to resolve this using webpacks loader.exec method, but ran into [a similar issue](https://github.com/webpack/webpack/issues/667).

I've since made an update to the development branch to catch the error when requiring a nunjucks environment config file that depends on webpack module resolution and instead fire a warning to console so that the templates still compile.

Provided you are not configuring the nunjucks environment with async filters and/or custom nunjucks extensions, your templates should still work even if the environment file depends on webpack module resolve.

Do you want to give this a try (using the develop branch) and see if it resolves your issue?

**Comment by dschissler** [comment]
I'm currently using `0.1.2` and this is my render module:

```javascript
'use strict';
// System
import nunjucks from 'nunjucks/browser/nunjucks-slim';
// Application
import locale from 'locale';

var env = new nunjucks.Environment();

env.addGlobal('gettext', function(message) {
  return locale.gettext(message);
});

env.addGlobal('t', function(message) {
  return locale.gettext(message);
});

env.addGlobal('ngettext', function(msg1, msg2, n) {
  return locale.ngettext(msg1, msg2, n);
});

env.addGlobal('n', function(msg1, msg2, n) {
  return locale.ngettext(msg1, msg2, n);
});

export default function(context, src) {
  let template = new nunjucks.Template(src, env);
  let html = template.render(context);
  return html;
};
```

Does this qualify as "custom nunjucks extensions"?

**Comment by dschissler** [comment]
Also, another point is that it would be nice to be able to wrap the nunjucks stuff so that it can return a function with whatever signature you need.

**Comment by at0g** [comment]
The code sample you posted above is not using custom tags/extensions - this is what I was referring to by [custom extensions](https://mozilla.github.io/nunjucks/api.html#addextension)

`0.1.2` is a very old version.

> Also, another point is that it would be nice to be able to wrap the nunjucks stuff 
> so that it can return a function with whatever signature you need.

Sorry, what do you mean by this? 
The loader does return a compiled template with the same signature as `new nunjucks.Template` - aside from configuring the nunjucks environment (optional), there is no need to reference nunjucks in your app code. EG.

```
var template = require('nunjucks!./my-template.nunj');
var html = template.render({});
```

**Comment by dschissler** [comment]
> 0.1.2 is a very old version.

Yes but its the one that I made to fit my needs and since I was early in the R&D process I stopped when I had it working (although its obviously compiling templates in the browser).  The later much more proper versions were unable to offer the necessary functionality and so if this new one does then it will be the first one yet.

It would just be nice to be able to do a little work in the loader to then [not need to overload view methods](https://github.com/AmpersandJS/ampersand-view/blob/master/ampersand-view.js#L322).  I overloaded it and its not a big deal but just would be nice.

Back to this below, so the locale data is obtained async but its not specifically a nunjucks async feature and that as far as nunjucks is concerned its just an object.  Is that what you mean below?

> Provided you are not configuring the nunjucks environment with async filters and/or custom nunjucks extensions, your templates should still work even if the environment file depends on webpack module resolve.

**Comment by dschissler** [comment]
Oh about testing it I'll try to do it by the end of the week.  I'm thrashing my code a lot right now.

**Comment by dschissler** [comment]
Wow good job!  I tested the develop branch and it works at least for using the locale module populated with data from a bundle loader.

Perhaps the warning message could supply an otherwise undocumented instruction to supply a query variable to the loader to remove the warning.

I'll be testing some nunjucks features like composing views and I'll post if there are any loader issues with that.  Otherwise I'm fully upgraded now :).

**Comment by dschissler** [comment]
Closing.  Please try to make the error message less yellow and every time.

**Comment by at0g** [comment]
Good to hear, glad it's working out for you.

**Comment by dschissler** [comment]
@at0g Did you merge this fix into master?

**Comment by at0g** [comment]
Yes it's merged. Tagged as 1.0.7
