### ISSUE TITLE
Work with babel may throw prop "MutationObserver" undefined.

### ISSUE THREAD

**Issue by yuffiy** [at0g/nunjucks-loader#32]
This mistake maybe happen on
https://github.com/mozilla/nunjucks/blob/master/browser/nunjucks-slim.js#L1340
can't work with 'use strict'.

I add ignore field on babelrc would fix this:

```js
{
  ignore: ['node_modules/nunjucks/*']
}
```

Are there better ways to solve problems？

Anything help.

Thanks. :)

**Comment by at0g** [comment]
The issue you're having is upstream from this lib - I can't really do anything about it here.

With babel, it makes sense to exclude `node_modules` that don't require transpiling as you'll get faster build time as a result.

**Comment by yuffiy** [comment]
@at0g 
:) thanks
