### ISSUE TITLE
Allow to assign a function directly to query.config

### ISSUE THREAD

**Issue by ghost** [at0g/nunjucks-loader#39]
Is it possible to, instead of passing a path to a module that exports a function, pass the function directly to the `query.config` option?

I think it would be great to be able to do something like

``` javascript
....
{
  test: /\.html$/,
  loader: 'nunjucks',
  query: {
    config: function (env) { ... }
  },
}
...
```

**Comment by at0g** [comment]
It would be nice, but...
The query is a string, and can also be used inline `require('nunjucks!tpl.njk?config=...')`.
It might be possible with `eval` (provided the supplied value is a string rather than a function), but I can see that approach coming with it's own set of problems.

**Comment by vtfn** [comment]
I may be misunderstanding something here, but I looked at the source and there is this chunk of code

```javascript
if (query.config) {
  pathToConfigure = query.config;
  try {
    var configure = require(query.config);
    configure(env);
  }
....
```

So I tought it would be possible to do something like this
```javascript
if (query.config) {
  pathToConfigure = query.config;
  try {
    var configure   
    if (typeof query.config === 'function')
      configure = query.config;
    else
      configure =  require(query.config);
    configure(env);
  }
....
```

I've forked this repo and tried to do this myself but, for some reason I really don't undestand, I couldn't get the tests to work in my machine.

**Comment by at0g** [comment]
@vtfn 
What was the problem you had with the tests - maybe I can help you out with that?

Regarding your previous comment:
```
if (typeof query.config === 'function')             // always false
console.log(typeof query.config === 'string') // always true
``
