### ISSUE TITLE
require Macro does nothing

### ISSUE THREAD

**Issue by jamesgorrie** [at0g/nunjucks-loader#41]
I have tried to include a macro into my app with no luck.

I am not sure if this is something missing from Nunjucks' API ([report](https://groups.google.com/forum/?fromgroups#!topic/nunjucks/oNMdE7I5aSU)) or from the loader.

e.g.
```HTML
{# macro.njk #}
{% macro toggler(controlsId, expanded = true, attributes = {}, innerHTML = "") %}
  {# make this a button #}
  <a href="#"
    role="button"
    {% for attr, val in attributes %}
      {{attr}}="{{val}}"
    {% endfor %}
    data-component="show-hide"
    aria-controls="{{controlsId}}"
    aria-expanded="{{expanded}}">
    {{innerHTML | safe}}
  </a>
{% endmacro %}
```

```JS
// app.js
import template from './location/to/macro/macro.njk';

// Not sure what the syntax is here, I've dug around and can't fund anything.
const rendered = template.toggler.render({ expanded: true, controlsId: 'nav' });
console.log(rendered);
```

**Comment by at0g** [comment]
This is expected behaviour - try importing and using the macro within a nunjucks template, then import and render the template in javascript. 

eg.
```
{# filename: template-using-macro.njk #}
{% import './macros.njk' as macros %}

{{ macros.toggler(expanded=true, controlsId: 'nav') }}
```

```
// filename: app.js
import template from './template-using-macro.njk';

const html = template.render();
console.log(html)
```

**Comment by jamesgorrie** [comment]
Problem is I want the JS to be able to create macros...

**Comment by at0g** [comment]
> Problem is I want the JS to be able to create macros

create or call?

if you want to be able to call macro's from js, simple answer is you can't - AFAIK nunjucks does not support this - the macros need to be imported into a nunjucks template and then the template is rendered. eg.

```
var app = express();

nunjucks.configure('views', {
    autoescape: true,
    express: app
});

app.get('/', function(req, res) {
    res.render('macro.njk'); // this won't work
});
```

If what you want is a callable template function that takes arguments, why not just use a template and pass the data context? You can then import and render the template from js.

**Comment by jamesgorrie** [comment]
Supposing this isn't an issue with the loader.

**Comment by daniel-thisnow** [comment]
i at least got as far as knowing my problem may be fixed by import & macro.... but I'm still a long way away
