### ISSUE TITLE
webpack package error

### ISSUE THREAD

**Issue by zhongzhuhua** [at0g/nunjucks-loader#42]
webpack run, bundle.js use in index.html

error:
Uncaught TypeError: Cannot read property 'MutationObserver' of undefined

error code: 
var BrowserMutationObserver = global.MutationObserver || global.WebKitMutationObserver;

**Comment by at0g** [comment]
@zhongzhuhua - can you please provide more information - what's the problem exactly?

**Comment by at0g** [comment]
@zhongzhuhua Closing this issue - feel free to reopen if it's a problem with this library and not your config.

**Comment by ediblecode** [comment]
If anyone comes across this, this issue is described in more detail here: https://github.com/mozilla/nunjucks/issues/520
