### ISSUE TITLE
How to use templates with TypeScript? 

### ISSUE THREAD

**Issue by daslicht** [at0g/nunjucks-loader#44]
How to import nunjucks templates using the es6 syntax , please?

eg this one : ```var tpl = require('./views/page.njk');```

**Comment by daslicht** [comment]
import * as tpl from './views/page.njk' ?

**Comment by at0g** [comment]
```
import tpl from './views/page.njk';

tpl.render({ message: 'hello es6' });
```

^ Bit off topic - how to use ES6 import syntax is not really an issue of this project

**Comment by daslicht** [comment]
Thank you for answering that illegal question anyway....

**Comment by daslicht** [comment]
Long time not tried but today again : 

![](http://i.imgur.com/En2ywVp.png)
