### ISSUE TITLE
'Include' tag should use nunjucks-loader by default

### ISSUE THREAD

**Issue by ukch** [at0g/nunjucks-loader#46]
I have Webpack set up to require template files using 'tmpl' as a loader name (`require('tmpl!/path/to/template/file')`). However, I would like to be able to include template files from within another template file using just the filename, like the following:

```html
<div class="content">
    {% include 'content.html' %}
</div>
```

At present, Webpack fails at the include line with the error:
> You may need an appropriate loader to handle this file type.

It seems to me that the only use-case for the `include` tag is to include an HTML file, not arbitrary JavaScript (or other formats supported by Webpack). Therefore, the `include` tag (and other similar tags such as `extends`) should go straight to the nunjucks loader.

**Comment by at0g** [comment]
Did you read the readme (particularly the part about configuring the loader)? 

Presuming you have configured the loader in webpack.config, you absolutely can `include` templates from within other template.

eg.
```
file: webpack.config.js

module.exports = {
   module: {
    loaders: [
      // use nunjucks loader for all .njk files
      { test: /\.njk$/, loader: 'nunjucks-loader }
    ]
  }
}


file: parent.njk
<div class="content">
  {% include './child.njk' %}
</div>

file: child.njk
it works!
```

If this doesn't solve your issue (I'm not clear on what that is), please share a repo reproducing the issue, or at a minimum the relevant webpack.config and template files.

**Comment by at0g** [comment]
@ukch I'm going to go ahead and close this issue - if you believe it's still a problem, feel free to reopen it.
