### ISSUE TITLE
{% extends TemplateVariable %}  doesn`t support?

### ISSUE THREAD

**Issue by Aaronphy** [at0g/nunjucks-loader#47]
folders 
```
templates/
     -----parent.html
     -----children.html
     -----test.js
```

children.html
```html
   {% extends './parent.html'  %}    or  {% extends  parentTpl %}
```

then 
```javascript
   let childTpl =  children.render()   //  it works 
   // another way  store the file path in a variable  it doesn`t work
   let childTpl =  children.render({  parentTpl : './parent.html' })  
```

It doesn`t support the dynamicly  extends?

**Comment by at0g** [comment]
I'm not surprised by this, internally the loader rewrites references within nunjucks templates (include, import, extends etc) to use webpacks require system.

What you're attempting to do is similar to this (which will fail static analysis)
```js
var pathToFoo = './path/to/foo.js';
var foo = require(pathToFoo);
```

If you really need dynamic includes, you could probably write a filter that uses `require.context`
