### ISSUE TITLE
2.4.6 breaks webpack builds

### ISSUE THREAD

**Issue by ntdb** [at0g/nunjucks-loader#49]
`Module build failed: TypeError: loaderUtils.getOptions is not a function`

Per @oh-ren's comment on #48, `loader-utils` needs to be updated to `1.0.0` or higher.

**Comment by at0g** [comment]
Fixed with #v2.4.7

**Comment by ntdb** [comment]
Thanks @at0g!

**Comment by TiagoGouvea** [comment]
For who are facing it, just ```npm install --save loader-utils``` to solve.
