### ISSUE TITLE
Version 2.4.7 broke compatibility

### ISSUE THREAD

**Issue by pmlt** [at0g/nunjucks-loader#50]
Hello, 

You have recently released version 2.4.7 of nunjucks-loader. However, in that release you have incremented the version of your dependency loader-utils from ^0.2.12 to ^1.0.0. This is a breaking change, so your 2.4.7 release violates the rules of semantic versioning.

In effect, this broke the build of multiple projects we are maintaining, because loader-utils version 1.x no longer compiles under the version of node JS we are using. Please fix your release.

**Comment by linsolas** [comment]
Hello,

Not perfectly sure it is related, but with `2.4.7` the loader does not get the query options. In the `loaderUtils.getOptions`, it expect an object with the `query` parameter ([code here](https://github.com/webpack/loader-utils/blob/master/lib/getOptions.js#L5-L6)) :

```js
function getOptions(loaderContext) {
	const query = loaderContext.query;
	if(typeof query === "string" && query !== "") {
		return parseQuery(loaderContext.query);
	}
	if(!query || typeof query !== "object") {
		// Not object-like queries are not supported.
		return null;
	}
	return query;
}
```

However, the nunjucks-loader [is giving a string](https://github.com/at0g/nunjucks-loader/blob/master/index.js#L28): 

```js
   if (!hasRun){
        var query = loaderUtils.getOptions(this.query);
```

and thus, the `query` object is null everytime. If I change the previous line to:

```js
   if (!hasRun){
        var query = loaderUtils.getOptions({query: this.query});
```
then it works as expected.

note: I'm using Webpack 1 in my project and my Webpack configuration is like that:

```
{
  test: /\.(njk|nunjucks)$/,
  loader: 'nunjucks-loader',
  query: {
    root: __dirname + '/pages',
    opts: {
      tags: {
        variableStart: '{$',
        variableEnd: '$}'
      }
    }
  }
```

**Comment by at0g** [comment]
`v2.4.8` reverts the changes in PR #48 and fixes this mess.
Will look at a 3.x branch for the move to loader utils 1.x
