### ISSUE TITLE
Is this usable to inject script tags ?

### ISSUE THREAD

**Issue by cyrilchapon** [at0g/nunjucks-loader#58]
Hey.

I landed here searching how I could inject my frontend build to a script tag inside a nunjucks template.

I'm building a plain, backend, express application using nunjucks templates, along with a webpack frontend javascript build.

I'm manually injecting webpack outputs to my templates with plain old `<script>` tags

Is this the place to be ?

**Comment by at0g** [comment]
I don't think so - this project is for using your nunjucks templates in webpack browser bundle(s).
