### ISSUE TITLE
Configurable `autoescape` is still enabled in browser environment

### ISSUE THREAD

**Issue by niksy** [at0g/nunjucks-loader#59]
If you pass custom `autoescape` value to `opts` object, it still defaults to `true` in browser environment. I think it’s related to this [browser environment codepath](https://github.com/at0g/nunjucks-loader/blob/master/index.js#L101).

If you create custom config file and change value there, it is applied in browser environment, but this seems like unecessary step.

Is there any reason why browser environment couldn’t also use passed options?

I also think this is somewhat related to issue #54.

**Comment by at0g** [comment]
Thanks for the bug report.
AFAIK, there is no reason not to use the passed options.

**Comment by niksy** [comment]
@at0g any chance to get this pushed as new version?
