### ISSUE TITLE
Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by brunowego** [at0g/nunjucks-loader#61]
I need a small help here,  take a look below to the error I am getting when execute:

```
ERROR in ./src/views/index.njk
Module build failed: TypeError: Cannot read property 'context' of undefined
    at Object.module.exports (/secret/example/node_modules/nunjucks-loader/index.js:76:57)
 @ ./src/entry.js 1:0-28
```

Take a look at this example here: https://github.com/brunowego/nunjucks-webpack-example

**Comment by Kiniamaro** [comment]
Same thing here, this is most likely due to a compatibility issue with webpack 4 that came out a couple days ago.

**Comment by bonesoul** [comment]
same here with webpack 4.x.
